-- MySQL Script generated by MySQL Workbench
-- Mon Jul  8 20:20:50 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema graduated_project
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `graduated_project` ;

-- -----------------------------------------------------
-- Schema graduated_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `graduated_project` DEFAULT CHARACTER SET utf8mb3 ;
USE `graduated_project` ;

-- -----------------------------------------------------
-- Table `graduated_project`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduated_project`.`users` ;

CREATE TABLE IF NOT EXISTS `graduated_project`.`users` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `Mail` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`User_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `graduated_project`.`files`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduated_project`.`files` ;

CREATE TABLE IF NOT EXISTS `graduated_project`.`files` (
  `File_id` INT NOT NULL AUTO_INCREMENT,
  `File_name` VARCHAR(60) NULL DEFAULT NULL,
  `User_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`File_id`),
  INDEX `User_id_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `User_id`
    FOREIGN KEY (`User_id`)
    REFERENCES `graduated_project`.`users` (`User_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `graduated_project`.`table_list`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduated_project`.`table_list` ;

CREATE TABLE IF NOT EXISTS `graduated_project`.`table_list` (
  `Table_id` INT NOT NULL AUTO_INCREMENT,
  `Table_name` VARCHAR(60) NULL DEFAULT NULL,
  `Script` TEXT NULL DEFAULT NULL,
  `x` VARCHAR(20) NULL DEFAULT NULL,
  `y` VARCHAR(20) NULL DEFAULT NULL,
  `File` INT NULL,
  PRIMARY KEY (`Table_id`),
  INDEX `File_id_idx2` (`File` ASC) VISIBLE,
  CONSTRAINT `fk_tablelist_ref_files`
    FOREIGN KEY (`File`)
    REFERENCES `graduated_project`.`files` (`File_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `graduated_project`.`foreign_key`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `graduated_project`.`foreign_key` ;

CREATE TABLE IF NOT EXISTS `graduated_project`.`foreign_key` (
  `FK_id` INT NOT NULL AUTO_INCREMENT,
  `From_tbl` VARCHAR(45) NOT NULL,
  `Ref_tbl` VARCHAR(45) NOT NULL,
  `From_col` VARCHAR(45) NOT NULL,
  `To_col` VARCHAR(45) NOT NULL,
  `File_id` INT NULL DEFAULT NULL,
  `table_id` INT NOT NULL,
  PRIMARY KEY (`FK_id`),
  INDEX `File_id_idx1` (`File_id` ASC) VISIBLE,
  INDEX `fk_foreignkey_ref_tablelist_idx` (`table_id` ASC) VISIBLE,
  CONSTRAINT `fk_foreignkey_ref_files`
    FOREIGN KEY (`File_id`)
    REFERENCES `graduated_project`.`files` (`File_id`),
  CONSTRAINT `fk_foreignkey_ref_tablelist`
    FOREIGN KEY (`table_id`)
    REFERENCES `graduated_project`.`table_list` (`Table_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `graduated_project`.`users`
-- -----------------------------------------------------
START TRANSACTION;
USE `graduated_project`;
INSERT INTO `graduated_project`.`users` (`User_id`, `Mail`) VALUES (1, 'abc@gmail.com');

COMMIT;


-- -----------------------------------------------------
-- Data for table `graduated_project`.`files`
-- -----------------------------------------------------
START TRANSACTION;
USE `graduated_project`;
INSERT INTO `graduated_project`.`files` (`File_id`, `File_name`, `User_id`) VALUES (1, 'my_schema', 1);

COMMIT;

